# escape=`
FROM mcr.microsoft.com/powershell:nanoserver-ltsc2022
USER ContainerAdministrator

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ADD release/windows/amd64/reqcheck.exe C:/bin/reqcheck.exe
ENTRYPOINT [ "C:\\bin\\reqcheck.exe" ]
